### ISSUE TITLE
NPM test throwes error

### ISSUE THREAD

**Issue by CKiOne** [cmdcolin/cra-webpack5-web-worker-example#1]
C:\Dev\Tests\cra-webpack5-web-worker-example-master\src\App.tsx:19
    const worker = new Worker(new URL('./deep-thought.ts', import.meta.url));

**Comment by cmdcolin** [comment]
it is mentioned in the README that import.meta.url doesn't work in jest. basically you have to create a non-webworker system for testing in jest...sorry for the two year reply delay :)
